import React from 'react';
import { View, Text } from 'react-native';
import PropTypes from 'prop-types';
import styles from './styles';

export const Icon = ({
	iconColor,
	backgroundColor,
	symbol,
	size,
	customStyles,
}) => {
	const style = { backgroundColor, ...customStyles };
	const iconStyle = { color: iconColor, ...size === 'small' ? styles.small : size === 'medium' ? styles.medium : styles.large, ...styles.icon };
	console.log(iconColor);

	let token = {
		ChevronUp: '',
		ChevronDown: '',
		ChevronRight: '',
		ChevronLeft: '',
		Edit: '',
		Add: '',
		Cancel: '',
		More: '',
		Settings: '',
		Pin: '',
		PinFill: '',
		Unpin: '',
		Link: '',
		Filter: '',
		KnowledgeArticle: '',
		Zoom: '',
		ZoomIn: '',
		ZoomOut: '',
		MapPin: '',
		MapPin2: '',
		LocaleLanguage: '',
		Search: '',
		Camera: '',
		Attach: '',
		Page: '',
		PageSolid: '',
		Forward: '',
		Back: '',
		Refresh: '',
		Share: '',
		Lock: '',
		Unlock: '',
		FavoriteStar: '',
		FavoriteStarFill: '',
		Unfavorite: '',
		Remove: '',
		Checkbox: '',
		CheckboxFill: '',
		CheckboxIndeterminate: '',
		CheckMark: '',
		Up: '',
		Down: '',
		Delete: '',
		Save: '',
		Cloud: '',
		PageLeft: '',
		PageRight: '',
		Error: '',
		Warning: '',
		GripperBarHorizontal: '',
		GripperBarVertical: '',
		Contact: '',
		ContactFill: '',
		ContactInfo: '',
		Calendar: '',
		CalendarFill: '',
		CalendarDay: '',
		CalendarWeek: '',
		Redo: '',
		Undo: '',
		Move: '',
		BrowsePhotos: '',
		Folder: '',
		FolderFill: '',
		FolderOpen: '',
		RightQuote: '',
		LeftQuote: '',
		RightDoubleQuote: '',
		LeftDoubleQuote: '',
		Help: '',
		SelectAll: '',
		Import: '',
		ImportAll: '',
		Photo: '',
		Picture: '',
		Sort: '',
		OpenFile: '',
		Tag: '',
		Library: '',
		People: '',
		Accept: '',
		Comment: '',
		Info: '',
		Health: '',
		ChevronUpSmall: '',
		ChevronDownSmall: '',
		ChevronLeftSmall: '',
		ChevronRightSmall: '',
		Unknown: '',
		ChevronUpMedium: '',
		ChevronDownMedium: '',
		ChevronLeftMedium: '',
		ChevronRightMedium: '',
		Media: '',
		Puzzle: '',
		Heart: '',
		HeartFill: '',
		Family: '',
		DateTime: '',
		POI: '',
		Unit: '',
		RadioButtonOff: '',
		RadioBullet2: '',
		PanMode: '',
		Hide: '',
		Export: '',
		Flow: '',
		Relationship: '',
	} [symbol] ?? '';

	return (
		<View style={style}>
			<Text style={iconStyle}>{token}</Text>
		</View>
	);
};

Icon.defaultProps = {
	symbol: 'Unknown',
	size: 'medium',
};

Icon.propTypes = {
	symbol: PropTypes.string.isRequired,
	size: PropTypes.oneOf(['small', 'medium', 'large']),
};